@Url = https://localhost:7224

### Register
POST {{Url}}/api/auth/register
Content-Type: application/json

{
  "userName": "testuser",
  "email": "testuser@example.com",
  "password": "Test@1234",
  "fullName": "Julian Shaw",
  "firstName": "Test",
  "lastName": "User"
}

### Login
POST {{Url}}/api/auth/login
Content-Type: application/json

{
  "userName": "testuser",
  "password": "Test@1234"
}
 

###
